# Generated by Django 6.1 on 2026-08-20 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing'), ('ENRICHING', 'Enriching'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterboxd_uri', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('watched_date', models.DateField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('rewatch', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='tmdb.movie')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='imports.importsession')),
            ],
            options={
                'indexes': [models.Index(fields=['import_session', 'watched_date'], name='imports_dia_import__8bd0a2_idx')],
                'unique_together': {('import_session', 'letterboxd_uri', 'watched_date')},
            },
        ),
        migrations.CreateModel(
            name='LikedFilmEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterboxd_uri', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_liked', models.DateField(blank=True, null=True)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_film_entries', to='imports.importsession')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_film_entries', to='tmdb.movie')),
            ],
            options={
                'unique_together': {('import_session', 'letterboxd_uri')},
            },
        ),
        migrations.CreateModel(
            name='RatingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterboxd_uri', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_entries', to='imports.importsession')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_entries', to='tmdb.movie')),
            ],
            options={
                'unique_together': {('import_session', 'letterboxd_uri')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterboxd_uri', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('added_date', models.DateField(blank=True, null=True)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='imports.importsession')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_entries', to='tmdb.movie')),
            ],
            options={
                'unique_together': {('import_session', 'letterboxd_uri')},
            },
        ),
    ]
