# Generated by Django 6.1 on 2026-08-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='favorite_letterboxd_uris',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='WatchedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterboxd_uri', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_entries', to='imports.importsession')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watched_entries', to='tmdb.movie')),
            ],
            options={
                'unique_together': {('import_session', 'letterboxd_uri')},
            },
        ),
    ]
