# Generated by Django 6.1 on 2026-08-21 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importsession_favorite_letterboxd_uris_watchedentry'),
        ('tmdb', '0003_titleyearlookup_is_tv_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterboxd_uri', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('watched_date', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('review', models.TextField(blank=True)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_entries', to='imports.importsession')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_entries', to='tmdb.movie')),
            ],
            options={
                'unique_together': {('import_session', 'letterboxd_uri', 'watched_date')},
            },
        ),
    ]
