# Generated by Django 6.1 on 2026-09-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_importsession_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='is_tv_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='likedfilmentry',
            name='is_tv_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratingentry',
            name='is_tv_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewentry',
            name='is_tv_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchedentry',
            name='is_tv_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlistentry',
            name='is_tv_show',
            field=models.BooleanField(default=False),
        ),
    ]
