# Generated by Django 6.1 on 2026-10-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_backfill_is_tv_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('letterboxd_url', models.URLField(blank=True, max_length=500)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='imports.importsession')),
            ],
        ),
        migrations.CreateModel(
            name='ListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('letterboxd_uri', models.URLField(blank=True, max_length=500)),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='imports.userlist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
