# Generated by Django 6.1 on 2026-08-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('tmdb_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('tmdb_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('profile_path', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('runtime_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=300)),
                ('overview', models.TextField(blank=True)),
                ('tmdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='tmdb.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.person')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('movie', 'person')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_members',
            field=models.ManyToManyField(related_name='acted_in', through='tmdb.Credit', to='tmdb.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='tmdb.person'),
        ),
        migrations.CreateModel(
            name='TitleYearLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tmdb.movie')),
            ],
            options={
                'unique_together': {('title', 'year')},
            },
        ),
    ]
