# Generated by Django 6.1 on 2026-08-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_country_movie_original_language_movie_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleyearlookup',
            name='is_tv_show',
            field=models.BooleanField(default=False),
        ),
    ]
