# Generated by Django 6.1 on 2026-09-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0004_remove_movie_director_movie_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
