# Generated by Django 6.1 on 2026-09-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0005_movie_vote_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('tmdb_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='movies', to='tmdb.keyword'),
        ),
    ]
